export const BRANDING = {
  name: 'DCPC - BAGONG PAG-ASA TRANSPORT COOPERATIVE',
  shortName: 'DCPC BAPAGTRANSCO',
  tagline: 'BAGONG PAG-ASA TRANSPORT COOPERATIVE',
  est: 'EST. 2021',
  location: 'Naga City, Camarines Sur',
  region: 'Bicol Region, Philippines',
  fullAddress: 'PAG-ASA ST VCS DEL ROSARIO NAGA CITY',
  logoUrl: '/dcpc-logo.png',
  fallbackLogoUrl: '/logo.png',
  contactNumber: '09123427581',
  email: 'dcpctransport@gmail.com',
  operatingHours: '4:00 AM - 9:00 PM Daily',
  routes: [
    { from: 'Pag-Asa St VCS Del Rosario Terminal', to: 'Naga City CBD / Central Bus Terminal', fare: '₱20.00', travelTime: '15 mins' },
    { from: 'Del Rosario Naga City', to: 'Magsaysay Ave / Plaza Quezon Loop', fare: '₱25.00', travelTime: '20 mins' },
    { from: 'Naga City Central Terminal', to: 'Pili Central / Bicol State College', fare: '₱35.00', travelTime: '30 mins' },
    { from: 'Pag-Asa St VCS Terminal', to: 'Concepcion Grande / Diversion Road', fare: '₱25.00', travelTime: '20 mins' },
  ],
};
