export const BRANDING = {
  name: 'DCPC - BAGONG PAG-ASA TRANSPORT COOPERATIVE',
  shortName: 'DCPC BAPAGTRANSCO',
  tagline: 'BAGONG PAG-ASA TRANSPORT COOPERATIVE',
  est: 'EST. 2021',
  location: 'Naga City, Camarines Sur',
  region: 'Bicol Region, Philippines',
  fullAddress: 'PAG-ASA ST VCS DEL ROSARIO NAGA CITY',
  primaryRoute: 'DEL ROSARIO - CONCEPCION - PANGANIBAN - CENTRO - VICE VERSA',
  routeStops: [
    'Del Rosario (Pag-Asa St VCS)',
    'Concepcion Grande / Pequeña',
    'Panganiban Drive',
    'Centro (Naga CBD / Plaza Quezon)',
  ],
  logoUrl: '/dcpc-logo.png',
  fallbackLogoUrl: '/logo.png',
  contactNumber: '09123427581',
  email: 'dcpctransport@gmail.com',
  operatingHours: '4:00 AM - 9:00 PM Daily',
  routes: [
    {
      title: 'Full Line (Del Rosario to Centro)',
      from: 'Del Rosario (Pag-Asa St VCS Terminal)',
      via: 'Concepcion - Panganiban Drive',
      to: 'Centro (Plaza Quezon / Naga CBD)',
      fare: '₱20.00 - ₱25.00',
      travelTime: '20 - 25 mins',
      direction: 'Inbound',
    },
    {
      title: 'Full Line (Centro to Del Rosario - Vice Versa)',
      from: 'Centro (Plaza Quezon / Naga CBD)',
      via: 'Panganiban Drive - Concepcion',
      to: 'Del Rosario (Pag-Asa St VCS Terminal)',
      fare: '₱20.00 - ₱25.00',
      travelTime: '20 - 25 mins',
      direction: 'Outbound',
    },
    {
      title: 'Del Rosario - Concepcion Segment',
      from: 'Pag-Asa St VCS Del Rosario',
      via: 'Maharlika Highway',
      to: 'Concepcion Grande / Pequeña',
      fare: '₱15.00 - ₱18.00',
      travelTime: '10 mins',
      direction: 'Two-way',
    },
    {
      title: 'Concepcion - Panganiban - Centro Segment',
      from: 'Concepcion Grande / Pequeña',
      via: 'Panganiban Drive (CBD II)',
      to: 'Centro (Plaza Quezon / Public Market)',
      fare: '₱15.00 - ₱18.00',
      travelTime: '12 mins',
      direction: 'Two-way',
    },
  ],
};
